services:
  - type: web
    name: rps15-server
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install && cd .. && npm install && npm run build:server
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        sync: false
